"""removed evaluations and replaced with TaskReview table

Revision ID: 69c415454ce3
Revises: 1a2e0feff638
Create Date: 2025-08-10 22:50:30.513939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c415454ce3'
down_revision = '1a2e0feff638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('evaluator_id', sa.INTEGER(), nullable=False),
    sa.Column('evaluated_user_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('evaluated_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('check_score_range')),
    sa.ForeignKeyConstraint(['evaluated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
