"""added get_kpi_for_month to User table

Revision ID: b7db3879ae6b
Revises: 69c415454ce3
Create Date: 2025-08-10 23:35:08.308390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7db3879ae6b'
down_revision = '69c415454ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_kpis', schema=None) as batch_op:
        batch_op.create_index('ix_monthlykpi_user_year_month', ['user_id', 'year', 'month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_kpis', schema=None) as batch_op:
        batch_op.drop_index('ix_monthlykpi_user_year_month')

    op.drop_table('monthly_kpis')
    # ### end Alembic commands ###
